### ISSUE TITLE
users/show.heml.erbのデザインを行う。

### ISSUE THREAD

**Issue by narisada014** [members-d23/dive23#67]
users/show.html.erbをツイッター風にデザインしてください。

**Comment by YoshihiroNakazawa** [comment]
@narisada014 
users/showは部品（パーシャル）で考えるとほとんど全てが含まれるのですが、show.html.erb、_tweet.html.erb、_user.html.erbあたりで分けたほうが良いのではないでしょうか。

**Comment by narisada014** [comment]
@YoshihiroNakazawa _tweetと_user以外の部分を作成するissueとしてこのissueは行いますね。

**Comment by narisada014** [comment]
@YoshihiroNakazawa @aki5454 このページのデザインなんですが、現在ツイッターと同様にcenterにタブを配置しようとしています。その場合パーシャル部分のツイート表示等もcenter配置にすることが必要となってくるのですがとりあえずcenterに配置する方向で進めてもいいでしょうか？どちらにせよ時間的にもう厳しいとは思いますが・・笑

**Comment by YoshihiroNakazawa** [comment]
@narisada014 
具体的にはどういうコードになるのでしょうか？

**Comment by YoshihiroNakazawa** [comment]
@narisada014 
雛形レベルで一度pushして頂いても良いかと思います。

**Comment by narisada014** [comment]
@YoshihiroNakazawa とりあえず画面のサイズごとに表示を変えるところまででき、パーシャル部分を作る段階に入れそうなのでpushします。先ほどmergeされた内容はこちらでgit mergeした方がいいですか？

**Comment by YoshihiroNakazawa** [comment]
@narisada014 
mergeおねがいします。
issues/#67はこちらでも内容を見てみます。

**Comment by YoshihiroNakazawa** [comment]
@narisada014 
確認しました。
そのままだと一覧が左ペインと被ってしまいますね。
tab-contentのブロックを別row扱いで適当な幅でcolを指定して、右に寄せれば良さそうです。

**Comment by narisada014** [comment]
@YoshihiroNakazawa 一応越川さん担当となっているのですがログイン画面やユーザー一覧等作り終わったら作業に移ります。なお、19時〜21時がDIVE10の最終授業のため一度作業から抜けます。

**Comment by YoshihiroNakazawa** [comment]
@narisada014 
_user.html.erbはホームの左ペイント類似したレイアウトなのでこちらで対応できますが、どうしますか？

**Comment by narisada014** [comment]
@YoshihiroNakazawa 現在ログインページに着手中です。まだ取り掛かっていないのでお願いしてもよろしいでしょうか？助かります！

**Comment by aki5454** [comment]
@YoshihiroNakazawa @narisada014
すいません。ちょっと作業出来そうにないです／(^o^)＼申し訳ございません／(^o^)＼

**Comment by YoshihiroNakazawa** [comment]
@aki5454 
了解しました。越川さんにアサインされているissueもできるところから対応します。
